sudo: required

language: java
jdk:
  - oraclejdk8
  
services:
  - docker
  
addons:
  sonarqube: true
env:
  global:
    - secure: fe4e74a05431f8b536f47b7211c94f833e1877ee # defines SONAR_TOKEN=abcdef0123456789

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=fe4e74a05431f8b536f47b7211c94f833e1877ee

after_success:
  - locate QCM-0.0.1-SNAPSHOT.war
  - docker build -t mbriatte/qcm:latest .
  - docker images
  - docker run mbriatte/qcm:latest --name webapp 
  - docker ps -a 
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push mbriatte/qcm:latest 
