 web:
  image: mbriatte/qcm:latest
  links:
  - db
  environment:
  - DATABASE_URL=postgresql://172.17.0.2:5432
  ports:
  - "8081:8080"
 db:
  image: "postgres:9.1"
  environment:
   - POSTGRES_DB=QCM
   - POSTGRES_USER=mika
   - POSTGRES_PASSWORD=mika